<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="user-Latitude-3440" failures="1" tests="1" name="Opencart test" time="3.218" errors="0" timestamp="2025-07-14T23:14:56 IST">
  <testcase classname="testCases.TC_003_LoginDDT" name="test_LoginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at testCases.TC_003_LoginDDT.getData(TC_003_LoginDDT.java:115)
... 29 more
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test_LoginDDT -->
</testsuite> <!-- Opencart test -->
